package cz.cuni.mff.xrg.odcs.commons.app.module.osgi.packages;

/**
 * Contains list of org.eclipse.rdf4j packages that will be exported from frontend and
 * backend.
 * 
 * @author Petyr
 * @author Jiri Tomes
 */
public final class Rdf4jPackages {

    /**
     * List of OSGI packages to export. Does not start nor end with separator.
     */
    public static final String PACKAGES =
            "org.eclipse.rdf4j.common.app,"
                    + "org.eclipse.rdf4j.common.app.config,"
                    + "org.eclipse.rdf4j.common.app.config.defaults,"
                    + "org.eclipse.rdf4j.common.app.logging,"
                    + "org.eclipse.rdf4j.common.app.logging.base,"
                    + "org.eclipse.rdf4j.common.app.logging.logback,"
                    + "org.eclipse.rdf4j.common.app.net,"
                    + "org.eclipse.rdf4j.common.app.util,"
                    + "org.eclipse.rdf4j.common.logging,"
                    + "org.eclipse.rdf4j.common.logging.base,"
                    + "org.eclipse.rdf4j.common.logging.file.logback,"
                    + "org.eclipse.rdf4j.common.platform,"
                    + "org.eclipse.rdf4j.common.platform.support,"
                    + "org.eclipse.rdf4j,"
                    + "org.eclipse.rdf4j.console,"
                    + "org.eclipse.rdf4j.http.client,"
                    + "org.eclipse.rdf4j.http.client.query,"
                    + "org.eclipse.rdf4j.http.protocol,"
                    + "org.eclipse.rdf4j.http.protocol.error,"
                    + "org.eclipse.rdf4j.http.protocol.transaction,"
                    + "org.eclipse.rdf4j.http.protocol.transaction.operations,"
                    + "org.eclipse.rdf4j.model,"
                    + "org.eclipse.rdf4j.model.datatypes,"
                    + "org.eclipse.rdf4j.model.impl,"
                    + "org.eclipse.rdf4j.model.util,"
                    + "org.eclipse.rdf4j.model.util.language,"
                    + "org.eclipse.rdf4j.model.vocabulary,"
                    + "org.eclipse.rdf4j.query,"
                    + "org.eclipse.rdf4j.query.dawg,"
                    + "org.eclipse.rdf4j.query.impl,"
                    + "org.eclipse.rdf4j.query.algebra,"
                    + "org.eclipse.rdf4j.query.algebra.evaluation,"
                    + "org.eclipse.rdf4j.query.algebra.evaluation.federation,"
                    + "org.eclipse.rdf4j.query.algebra.evaluation.function,"
                    + "org.eclipse.rdf4j.query.algebra.evaluation.function.datetime,"
                    + "org.eclipse.rdf4j.query.algebra.evaluation.function.hash,"
                    + "org.eclipse.rdf4j.query.algebra.evaluation.function.numeric,"
                    + "org.eclipse.rdf4j.query.algebra.evaluation.function.rdfterm,"
                    + "org.eclipse.rdf4j.query.algebra.evaluation.function.string,"
                    + "org.eclipse.rdf4j.query.algebra.evaluation.impl,"
                    + "org.eclipse.rdf4j.query.algebra.evaluation.iterator,"
                    + "org.eclipse.rdf4j.query.algebra.evaluation.limited,"
                    + "org.eclipse.rdf4j.query.algebra.evaluation.limited.iterator,"
                    + "org.eclipse.rdf4j.query.algebra.evaluation.util,"
                    + "org.eclipse.rdf4j.query.algebra.helpers,"
                    + "org.eclipse.rdf4j.query.parser,"
                    + "org.eclipse.rdf4j.query.parser.serql,"
                    + "org.eclipse.rdf4j.query.parser.serql.ast,"
                    + "org.eclipse.rdf4j.query.parser.sparql,"
                    + "org.eclipse.rdf4j.query.parser.sparql.ast,"
                    + "org.eclipse.rdf4j.query.resultio,"
                    + "org.eclipse.rdf4j.query.resultio.helpers,"
                    + "org.eclipse.rdf4j.query.resultio.binary,"
                    + "org.eclipse.rdf4j.query.resultio.sparqljson,"
                    + "org.eclipse.rdf4j.query.resultio.sparqlxml,"
                    + "org.eclipse.rdf4j.query.resultio.text,"
                    + "org.eclipse.rdf4j.query.resultio.text.csv,"
                    + "org.eclipse.rdf4j.query.resultio.text.tsv,"
                    + "org.eclipse.rdf4j.repository,"
                    + "org.eclipse.rdf4j.repository.base,"
                    + "org.eclipse.rdf4j.repository.config,"
                    + "org.eclipse.rdf4j.repository.dataset,"
                    + "org.eclipse.rdf4j.repository.dataset.config,"
                    + "org.eclipse.rdf4j.repository.event,"
                    + "org.eclipse.rdf4j.repository.event.base,"
                    + "org.eclipse.rdf4j.repository.event.util,"
                    + "org.eclipse.rdf4j.repository.http,"
                    + "org.eclipse.rdf4j.repository.http.config,"
                    + "org.eclipse.rdf4j.repository.manager,"
                    + "org.eclipse.rdf4j.repository.manager.util,"
                    + "org.eclipse.rdf4j.repository.sail,"
                    + "org.eclipse.rdf4j.repository.sail.config,"
                    + "org.eclipse.rdf4j.repository.sail.helpers,"
                    + "org.eclipse.rdf4j.repository.sparql,"
                    + "org.eclipse.rdf4j.repository.sparql.config,"
                    + "org.eclipse.rdf4j.repository.sparql.query,"
                    + "org.eclipse.rdf4j.repository.util,"
                    + "org.eclipse.rdf4j.rio,"
                    + "org.eclipse.rdf4j.rio.binary,"
                    + "org.eclipse.rdf4j.rio.helpers,"
                    + "org.eclipse.rdf4j.rio.n3,"
                    + "org.eclipse.rdf4j.rio.ntriples,"
                    + "org.eclipse.rdf4j.rio.rdfxml,"
                    + "org.eclipse.rdf4j.rio.rdfxml.util,"
                    + "org.eclipse.rdf4j.rio.trig,"
                    + "org.eclipse.rdf4j.rio.trix,"
                    + "org.eclipse.rdf4j.rio.turtle,"
                    + "org.eclipse.rdf4j.rio.jsonld,"
                    + "org.eclipse.rdf4j.runtime,"
                    + "org.eclipse.rdf4j.sail,"
                    + "org.eclipse.rdf4j.sail.config,"
                    + "org.eclipse.rdf4j.sail.helpers,"
                    + "org.eclipse.rdf4j.sail.memory,"
                    + "org.eclipse.rdf4j.sail.memory.config,"
                    + "org.eclipse.rdf4j.sail.memory.model,"
                    + "org.eclipse.rdf4j.sail.nativerdf,"
                    + "org.eclipse.rdf4j.sail.nativerdf.btree,"
                    + "org.eclipse.rdf4j.sail.nativerdf.config,"
                    + "org.eclipse.rdf4j.sail.nativerdf.datastore,"
                    + "org.eclipse.rdf4j.sail.nativerdf.model,"
                    + "org.eclipse.rdf4j.sail.rdbms,"
                    + "org.eclipse.rdf4j.sail.rdbms.algebra,"
                    + "org.eclipse.rdf4j.sail.rdbms.algebra.base,"
                    + "org.eclipse.rdf4j.sail.rdbms.algebra.factories,"
                    + "org.eclipse.rdf4j.sail.rdbms.config,"
                    + "org.eclipse.rdf4j.sail.rdbms.evaluation,"
                    + "org.eclipse.rdf4j.sail.rdbms.exceptions,"
                    + "org.eclipse.rdf4j.sail.rdbms.iteration,"
                    + "org.eclipse.rdf4j.sail.rdbms.iteration.base,"
                    + "org.eclipse.rdf4j.sail.rdbms.managers,"
                    + "org.eclipse.rdf4j.sail.rdbms.managers.base,"
                    + "org.eclipse.rdf4j.sail.rdbms.managers.helpers,"
                    + "org.eclipse.rdf4j.sail.rdbms.model,"
                    + "org.eclipse.rdf4j.sail.rdbms.mysql,"
                    + "org.eclipse.rdf4j.sail.rdbms.optimizers,"
                    + "org.eclipse.rdf4j.sail.rdbms.postgresql,"
                    + "org.eclipse.rdf4j.sail.rdbms.schema,"
                    + "org.eclipse.rdf4j.sail.rdbms.util,"
                    + "org.eclipse.rdf4j.util.iterators,"
                    + "org.eclipse.rdf4j.common.io,"
                    + "org.eclipse.rdf4j.common.iteration,"
                    + "org.eclipse.rdf4j.common.lang,"
                    + "org.eclipse.rdf4j.common.lang.service,"
                    + "org.eclipse.rdf4j.common.net,"
                    + "org.eclipse.rdf4j.common.text,"
                    + "org.eclipse.rdf4j.common.xml";
}
